spring.application.name=dwese2526-ticketlogger-api-pvp


spring.datasource.url=jdbc:mariadb://localhost:3306/ticket-logger-webapp
spring.datasource.username=PedroVp
spring.datasource.password=Pvp2025
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10

jwt.keystore.path=fake
jwt.keystore.alias=fake
jwt.keystore.password=fake
jwt.private.key=fake
jwt.public.key=fake

app.upload-root=app.upload-root=C:/Users/pedro/IdeaProjects/dwese2526-ticketlogger-images

spring.web.resources.static-locations=classpath:/static/,file:${app.upload-root}/

spring.security.oauth2.client.registration.github.client-id=${Ov23lipiZk089n1nu5UG}
spring.security.oauth2.client.registration.github.client-secret=${ee6aafb11dd80ac071c165a25802215b8085df4e}
spring.security.oauth2.client.registration.github.scope=read:user
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user

spring.security.oauth2.client.provider.github.user-name-attribute=login

spring.security.oauth2.client.registration.github.client-id=Ov23lipiZk089n1nu5UG
spring.security.oauth2.client.registration.github.client-secret=f615572dc3625d6708162cf119873971db775ec2
spring.security.oauth2.client.registration.github.scope=read:user
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user

spring.security.oauth2.client.provider.github.user-name-attribute=login



spring.mail.from="TicketLogger"
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Tu cuenta Gmail completa
spring.mail.username=pedrobananacla@gmail.com
# CONTRASEÑA DE APLICACIÓN (App Password), no tu contraseña normal
spring.mail.password=zjeztfwirakvzqvu
# SMTP auth + TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Base pública REAL (la que ve el usuario en el navegador)
app.public-base-url=http://localhost:8080


# Ruta (por si cambia) del formulario de reset
app.password-reset.path=/auth/reset-password