spring.application.name=dwese2526-ticketlogger-webapp-pvp

# Forzado a la inicializacion del datasource con los archivos schema.sql y data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.messages.encoding=UTF-8
